### ISSUE TITLE
Support for passing user IDs for GDPR removal

### ISSUE THREAD

**Issue by littensy** [nezuo/lapis#21]
Is there support for `DataStore.SetAsync`'s [`userIds`](https://create.roblox.com/docs/reference/engine/classes/GlobalDataStore#SetAsync) parameter (or [`UpdateAsync`](https://create.roblox.com/docs/reference/engine/classes/GlobalDataStore#UpdateAsync)'s version of it) to help with GDPR removal requests? If not, is it planned?

**Comment by nezuo** [comment]
It's not currently supported. It's something I do want to add, I just haven't had a need for it yet.

**Comment by nezuo** [comment]
The API I'm considering right now is the following:

`Collection:load(key: string, defaultUserIds: { number })`
`Document:addUserId(userId: number)`
`Document:removeUserId(userId: number)`

`defaultUserIds` will only be used if the document doesn't already have any user ids set.

@littensy How do you feel about this?

**Comment by nezuo** [comment]
I realized that `DataStoreKeyInfo:GetUserIds()` will always return a table. The only way to know that the user ids have not been edited is when the key has never been set before. I'm thinking the `defaultUserIds` will only be used when the document is loaded for the first time.

**Comment by littensy** [comment]
It sounds good to me!
