### ISSUE TITLE
Implement a read-only mode

### ISSUE THREAD

**Issue by Nidoxs** [nezuo/lapis#44]
It would be useful to have a way to read a player's data while they're not in the game. For example, if there's a leaderboard system where it shows the top 3 players on podiums and you want to show things they own like skins, guns etc. The read-only feature would allow you to load their data and hold it temporarily to extract the value(s) you need.

I believe ProfileService has a [similar feature.](https://madstudioroblox.github.io/ProfileService/api/#profilestoreviewprofileasync)

Thanks! 👍

**Comment by nezuo** [comment]
Thanks for the issue, Lapis should definitely have this feature!

**Comment by jackTabsCode** [comment]
Yeah, having a way to read data without imposing a session lock would be great!

**Comment by nezuo** [comment]
I've been thinking about this and I'm not sure how it should work with migrations. Would you expect this to return API to return data with an outdated migration version?

**Comment by sasial-dev** [comment]
Maybe it runs the migration code locally but doesn't save that data back?

**Comment by sasial-dev** [comment]
Either way feels like it's a 'gotcha' territory.

**Comment by Nidoxs** [comment]
> Maybe it runs the migration code locally but doesn't save that data back?

I think applying a temporary unsaved migration is a necessary compromise for the proposed read-only mode.

I certainly don't have a use case for reading data that is out of date, so I think the natural step there is just running whatever migration is needed to bring the data up to date.

**Comment by nezuo** [comment]
Even if we did run the migration, you could have a situation where a server reads a document with a migration version higher than its own.

**Comment by sasial-dev** [comment]
That could still happen on it's normal write mode though? So I don't think it's in the scope of this issue?

**Comment by nezuo** [comment]
If you load a document that has a higher migration version than the servers, it will error and not load the document. We could do that here as well. I just don't know the specific use-cases people have for a read-only mode, so I don't know if that's acceptable.

**Comment by jackTabsCode** [comment]
I think it makes the most sense to return the data migrated to the version that the server calling it expects.

**Comment by nezuo** [comment]
> I think it makes the most sense to return the data migrated to the version that the server calling it expects.

I agree, but if it is passed the server's migration version, you would expect it to error then?

**Comment by jackTabsCode** [comment]
> > I think it makes the most sense to return the data migrated to the version that the server calling it expects.
> 
> I agree, but if it is passed the server's migration version, you would expect it to error then?

Yes

**Comment by nezuo** [comment]
Resolved with #59.
